In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

date = pd.read_csv('/content/drive/MyDrive/orders.csv')
time = pd.read_csv('/content/drive/MyDrive/messages.csv')

Mounted at /content/drive

In [ ]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [ ]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [ ]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [ ]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## **Working with Dates**

In [ ]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [ ]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [ ]:
#extract year
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
305 2019-07-05          25       18       1       2019
805 2019-11-28        6339       26       7       2019
95  2019-04-02        5383       11      24       2019
120 2018-11-19        2646       26       2       2018
106 2019-01-20        6592       25      11       2019

In [ ]:
#extract month
date['date_month_no'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [ ]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month_no date_dow_name
0 2019-12-10       2019             12       Tuesday
1 2018-08-15       2018              8     Wednesday
2 2018-10-23       2018             10       Tuesday
3 2019-08-17       2019              8      Saturday
4 2019-01-06       2019              1        Sunday

In [ ]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month_no date_dow_name  date_is_weekend
0 2019-12-10       2019             12       Tuesday                0
1 2018-08-15       2018              8     Wednesday                0
2 2018-10-23       2018             10       Tuesday                0
3 2019-08-17       2019              8      Saturday                1
4 2019-01-06       2019              1        Sunday                1

In [ ]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 3, 10, 10, 23, 16, 883010)

In [ ]:
today - date['date']

0     2282 days 10:23:16.883010
1     2764 days 10:23:16.883010
2     2695 days 10:23:16.883010
3     2397 days 10:23:16.883010
4     2620 days 10:23:16.883010
                 ...
995   2710 days 10:23:16.883010
996   2651 days 10:23:16.883010
997   2499 days 10:23:16.883010
998   2564 days 10:23:16.883010
999   2338 days 10:23:16.883010
Name: date, Length: 1000, dtype: timedelta64[ns]

In [ ]:
(today - date['date']).dt.days

0      2282
1      2764
2      2695
3      2397
4      2620
       ...
995    2710
996    2651
997    2499
998    2564
999    2338
Name: date, Length: 1000, dtype: int64

In [ ]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [ ]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [ ]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [ ]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [ ]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [ ]:
today - time['date']

0     4468 days 09:33:16.883010
1     4332 days 10:43:16.883010
2     4818 days 10:02:16.883010
3     4120 days 09:52:16.883010
4     4517 days 11:12:16.883010
                 ...
995   5107 days 09:33:16.883010
996   4428 days 11:09:16.883010
997   4893 days 10:46:16.883010
998   5009 days 10:49:16.883010
999   4281 days 10:58:16.883010
Name: date, Length: 1000, dtype: timedelta64[ns]

In [ ]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.860696e+08
1      3.743234e+08
2      4.163113e+08
3      3.560035e+08
4      3.903091e+08
           ...
995    4.412792e+08
996    3.826194e+08
997    4.227940e+08
998    4.328166e+08
999    3.699179e+08
Name: date, Length: 1000, dtype: float64